### ISSUE TITLE
Installing zprocess from the labscript-suite conda channel does not install windows requirements

### ISSUE THREAD

**Issue by dihm** [chrisjbillington/zprocess#15]
Noticed this when running a new install. You tend to get everything but `pywin32` and `windows-curses`, which then causes silent crashes of zprocess before any suite module's error handling is set up. 

This is what I get installing zprocess into a new environment from the conda channel
```shell
# Name                    Version                   Build  Channel
ca-certificates           2021.10.26           haa95532_2
certifi                   2021.10.8        py39haa95532_0
openssl                   1.1.1l               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pip                       21.2.4           py39haa95532_0
pyparsing                 3.0.4              pyhd3eb1b0_0
python                    3.9.7                h6244533_1
setuptools                58.0.4           py39haa95532_0
setuptools-scm            6.3.2              pyhd3eb1b0_0
sqlite                    3.36.0               h2bbff1b_0
tomli                     1.2.2              pyhd3eb1b0_0
tzdata                    2021e                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.0             pyhd3eb1b0_1
wincertstore              0.2              py39haa95532_2
zprocess                  2.20.2                   py39_0    labscript-suite
```

Here is what I get after removing it and installing from pip
```shell
# Name                    Version                   Build  Channel
ca-certificates           2021.10.26           haa95532_2
certifi                   2021.10.8        py39haa95532_0
openssl                   1.1.1l               h2bbff1b_0
packaging                 21.3                     pypi_0    pypi
pip                       21.2.4           py39haa95532_0
pyparsing                 3.0.6                    pypi_0    pypi
python                    3.9.7                h6244533_1
pywin32                   303                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
setuptools                58.0.4           py39haa95532_0
setuptools-scm            6.3.2                    pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0
tomli                     2.0.0                    pypi_0    pypi
tzdata                    2021e                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.0             pyhd3eb1b0_1
wincertstore              0.2              py39haa95532_2
windows-curses            2.3.0                    pypi_0    pypi
zprocess                  2.20.2                   pypi_0    pypi
```

**Comment by chrisjbillington** [comment]
Thanks. Might be a bug in setuptools-conda, will check if it's generating recipes with the correct dependencies.

**Comment by chrisjbillington** [comment]
I don't know if this is a recent change in setuptools or whatnot (if not, unsure how we haven't noticed this before!), but from setuptools-conda's perspective, these are all "extras-require" requirements:

zprocess.egg-info/requires.txt:

```
pyzmq>=18.0
setuptools_scm

[:python_version < "3.8"]
importlib_metadata

[:python_version == "2.7"]
ipaddress
subprocess32
enum34
pathlib

[:sys_platform == "win32"]
pywin32
windows-curses
```

So setuptools-conda will have to inspect `setuptools.Command.distribution.install_requires` (which contains only `pyzmq` and `setuptools_scm`) *and* `setuptools.Command.distribution.extras_requires` that has the rest - but somehow exclude actual extras that aren't just environment markers. Is those prefixed colons meaningful, does that imply the "extras" section is an environment marker? If so, would be easy to read them.

Would be better if it could just get the raw list of requirements with the environment markers, which it is already designed to parse - all I'm gonna be doing is recreating that out of the extras-require details.

Just documenting here what I found out so far, will fix in setuptools-conda when I have time.

**Comment by chrisjbillington** [comment]
Fixed in setuptools-conda, and rebuilt zprocess as v2.20.3 (building now). The conda packages appear to have the correct dependencies now.

**Comment by dihm** [comment]
Wow! Definitely did not intend for you to do any work on holiday! Stuff just came up when talking to an old lab-mate and wanted to record them so I didn't forget. However, as always, thanks for a speedy fix!

Happy holidays!

**Comment by chrisjbillington** [comment]
Oh I definitely feel zero obligation to do anything, but it caught my attention.

Merry Christmas!
